apiVersion: argoproj.io/v1alpha1
kind: ArgoCDExtension
metadata:
  name: test
  # finalizers:
  #   - extensions-finalizer.argocd.argoproj.io
spec:
  sources:
    # - git:
    #     url: https://github.com/argoproj-labs/argocd-example-extension.git
    - web:
        url: https://github.com/Kamaroth92/argo-cd-ui-test/raw/main/extensions/hello-world/dist/extension.tar