apiVersion: argoproj.io/v1alpha1
kind: ArgoCDExtension
metadata:
  name: hello-world
  labels:
    tab: "Application"
    icon: "fa-book"
  finalizers:
    - extensions-finalizer.argocd.argoproj.io
spec:
  sources:
    - web:
        url: https://github.com/argoproj-labs/argocd-example-extension/releases/download/v0.1.0/extension.tar