apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: extensions-pipeline
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: kubernetes/extensions
    repoURL: https://github.com/Kamaroth92/argo-cd-ui-test.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true