apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

- application-pipeline-controller.yaml
- extensions-pipeline-controller.yaml
components:
- https://github.com/argoproj-labs/argocd-extensions/manifests

patchesStrategicMerge:
- cm.yaml