apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-com
  namespace: default
spec:
  # Secret names are always required.
  secretName: example-com-tls
  commonName: example.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    