apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: podinfo
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
      - cluster: tst
        url: https://kubernetes.default.svc
      - cluster: prod
        url: https://kubernetes.default.svc
        
  template:
    metadata:
      name: '{{cluster}}-podinfo'
    spec:
      project: default
      source:
        repoURL: https://github.com/stefanprodan/podinfo.git
        targetRevision: HEAD
        path: kustomize
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}'